import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

final stations = {

  //Middle and Mustapha


  "ABEKA LAPAZ" : "Mustapha",
  "ABREPO KESE" : "Anthony",
  "ABREPO KUMA" : "Anthony",
  "ACP POKUASE" : "Mustapha",
  "ADENTA-AVIATION ROAD" : "Mustapha",
  "ADJRINGANOR" : "Mustapha",
  "AFRANCHO" : "Anthony",
  "AFRANCHO NO.2" : "Anthony",
  "AGBOGBA" : "Mustapha",
  "AHAFO HWIDIEM" : "Mustapha",
  "AHODWO ROUNDABOUT" : "Anthony",
  "AKROPONG" : "Mustapha",
  "AKUMADAN" : "Mustapha",
  "AKYAWKROM" : "Anthony",
  "ALBERT DADZIE(BATANYAA)" : "Mustapha",
  "AMAKOM" : "Anthony",
  "AMANFROM BAREKESE" : "Anthony",
  "AMPOMAH JUNCTION" : "Mustapha",
  "ANYAA MARKET" : "Mustapha",
  "ASAFO MARKET" : "Anthony",
  "ASOKORE MAMPONG" : "Anthony",
  "ASONABA ODUOM" : "Anthony",
  "ATASEMANSO" : "Anthony",
  "AYIGYA" : "Anthony",
  "AYORYA" : "Mustapha",
  "BANTAMA" : "Anthony",
  "BANDA NKWANTA" : "Mustapha",
  "BECHEM TEPA JUNCTION" : "Mustapha",
  "BEDIESO-OBUASI" : "Anthony",
  "BENUE NKWANTA" : "Mustapha",
  "BEKWAI ROUNDABOUT" : "Anthony",
  "BEREKUM MAIN" : "Mustapha",
  "BEREKUM SEIKWA RD" : "Mustapha",
  "BEREKUM DOMFETE" : "Mustapha",
  "BEREKUM-DORMAA ROAD" : "Mustapha",
  "BIBIANI LINESO" : "Mustapha",
  "BIBIANI MANUKROM" : "Mustapha",
  "BOANKRA" : "Anthony",
  "BOMFA JUNCTION" : "Anthony",
  "BREAMANG RICHAM" : "Anthony",
  "BREMAN UGC" : "Anthony",
  "BUOKROM" : "Anthony",
  "BUI JAMA" : "Mustapha",
  "DAABAN" : "Anthony",
  "DICHEMSO" : "Anthony",
  "DORMA AHENKRO" : "Mustapha",
  "DROBO" : "Mustapha",
  "DUNKWA ATECHEM" : "Anthony",
  "EFFIDUASE" : "Anthony",
  "EJISU" : "Anthony",
  "EJURA HIGHSTREET" : "Anthony",
  "EMENA" : "Anthony",
  "FIAPRE" : "Mustapha",
  "GOASO HWEDIEM ROAD" : "Mustapha",
  "JACHIE PRAMSO" : "Anthony",
  "JUABEN - YAW NKRUMAH" : "Anthony",
  "JUABEN NO.1" : "Anthony",
  "KAASE" : "Anthony",
  "KEGYASE" : "Anthony",
  "KEJETIA-MBROM" : "Anthony",
  "KENTINKRONO KNUST" : "Anthony",
  "KINTAMPO" : "Mustapha",
  "MIM OPPONKROM" : "Mustapha",
  "KONONGO ODUMASE" : "Anthony",
  "KOTWI" : "Anthony",
  "KPESHIE" : "Anthony",
  "KROFROM" : "Anthony",
  "KROMOASE" : "Anthony",
  "KUBEASE" : "Anthony",
  "KRONUM ABOUHIA" : "Anthony",
  "KWABENYA TAXI RANK" : "Anthony",
  "KWAMO" : "Anthony",
  "LA  NKWANTANANG" : "Anthony",
  "MAASE" : "Anthony",
  "MAMPONG BYPASS" : "Anthony",
  "MAMPONG TOWN" : "Anthony",
  "MANHYIA" : "Anthony",
  "MANHYIA HOSPITAL" : "Anthony",
  "MFUM BABIANIHA" : "Anthony",
  "MEMPEASEM" : "Anthony",
  "NEW BORTIANOR" : "Anthony",
  "NEW KRAPA" : "Anthony",
  "NEW KENTINKRONO" : "Anthony",
  "NKAWIE" : "Mustapha",
  "NKORANZA" : "Mustapha",
  "NYANKYERENIASI" : "Anthony",
  "OFFINSO ABOFOUR" : "Mustapha",
  "OFFINSO ASAMANKAMA" : "Mustapha",
  "OFFINSO DENASE" : "Mustapha",
  "OFFINSO DENTIN" : "Mustapha",
  "OFFINSO SAKAMU" : "Mustapha",
  "OFFINSO TOLLBOTH" : "Mustapha",
  "OFFINSO TUTUASE 1" : "Mustapha",
  "OLD TAFO" : "Anthony",
  "OPEIKUMA" : "Anthony",
  "PANKRONU KODUA JUNCTION" : "Anthony",
  "PAKYI NO. 1" : "Anthony",
  "Pokuase Junction" : "Anthony",
  "REXFORD DZAMPSON(APOWA)" : "Anthony",
  "SAFEWHEEL" : "Anthony",
  "SAMPA" : "Mustapha",
  "SANKORE" : "Mustapha",
  "SANTASI ROUNDABOUT" : "Anthony",
  "SANTASI-ANYINAM" : "Anthony",
  "SEFWI DWENASE" : "Mustapha",
  "SEFWI BODI" : "Mustapha",
  "SUAME ROUNDABOUT" : "Anthony",
  "SUNYANI ABESIM" : "Mustapha",
  "SUNYANI BYPASS" : "Mustapha",
  "SUNYANI NEW DORMAA RD" : "Mustapha",
  "SUNYANI ODUMASI" : "Mustapha",
  "SUNYANI RIDGE" : "Mustapha",
  "SUNYANI TANOSO" : "Mustapha",
  "SUNYANI ZONGO" : "Mustapha",
  "TAFO WESLEY" : "Anthony",
  "TAKYIKROM" : "Anthony",
  "TANOSO MELCOM" : "Anthony",
  "TECHIMAN ANYINABREM" : "Mustapha",
  "Techiman Bankoma Estate" : "Mustapha",
  "TECHIMAN KUNTUNSO" : "Mustapha",
  "TECHIMAN MARKET" : "Mustapha",
  "TECHIMAN TUOBODOM ROAD 1" : "Mustapha",
  "TUOBODOM RD 2" : "Mustapha",
  "TEWOBAABI" : "Anthony",
  "WAMFIE" : "Mustapha",
  "WENCHI MAIN" : "Mustapha",
  "WENCHI WA ROAD" : "Mustapha",
  "YAWKWEI" : "Anthony",
  "YEJI" : "Anthony",



  //North North West Stations
  "AIRPORT ROAD, TAMALE" : "Simon",
  "BAMAHU" : "Simon",
  "BAWKU BY-PASS" : "Simon",
  "BAWKU MAIN" : "Simon",
  "BIMBILLA" : "Simon",
  "BOLGA - BAWKU ROAD" : "Simon",
  "BOLGA MAIN" : "Simon",
  "BOLGA SOE" : "Simon",
  "BONGO" : "Simon",
  "BUIPE" : "Simon",
  "BURMA CAMP" : "Simon",
  "CENTRAL VITTIN" : "Simon",
  "DENCHIRA" : "Simon",
  "DORIMON" : "Simon",
  "DUNGU" : "Simon",
  "GBAWE ZERO" : "Simon",
  "HAIN" : "Simon",
  "HOSPITAL ROAD" : "Simon",
  "JISONAYILY - TAMALE" : "Simon",
  "JUBA BARRACKS - BURMA CAMP" : "Simon",
  "KALADAN" : "Simon",
  "KONGO" : "Simon",
  "KORLE GONNO" : "Simon",
    "LAWRA" : "Simon",
  "NAVRONGO" : "Simon",
  "RICE CITY - TAMALE" : "Simon",
  "RIVOLI" : "Simon",
  "SALAGA" : "Simon",
  "SANDEMA" : "Simon",
  "SOUTH VITTIN" : "Simon",
  "TUMU 1" : "Simon",
  "TUMU NO.2" : "Simon",
  "WA AIRPORT 1" : "Simon",
  "WA AIRPORT 2" : "Simon",
  "WA MAIN" : "Simon",
  "WA POLY RD" : "Simon",
  "WA PWD" : "Simon",
  "WALEWALE NALERIGU" : "Simon",
  "YENDI ROAD" : "Simon",
  "YENDI TOWN" : "Simon",
  "ZEBILLA" : "Simon",

  //Kobby Stations
  "ABURA STADIUM S/S" : "Kobby",
  "ADANDZIE" : "Kobby",
  "ADISADEL (CAPE COAST)" : "Kobby",
  "AGONA AMENFI" : "Kobby",
  "AJUMAKO" : "Kobby",
  "AKATSI BY PASS" : "Kobby",
  "AKWAKROM" : "Kobby",
  "ANAJIFIE" : "Kobby",
  "APREMDO" : "Kobby",
  "APOWA" : "Kobby",
  "ASSIN BROFOYEDURU" : "Kobby",
  "ASSIN PRASO" : "Kobby",
  "AIRPORT ROUND ABT - TAKORADI" : "Kobby",
  "BAKAEKYIRE S/S" : "Kobby",
  "BATANYAA" : "Kobby",
  "BEPOSO  F/S" : "Kobby",
  "BOGOSO  APPIATE" : "Kobby",
  "BOGOSO ELCON" : "Kobby",
  "BREMAN ASIKUMA" : "Kobby",
  "ELUBO" : "Kobby",
  "ENCHI" : "Kobby",
  "ESSIAMA" : "Kobby",
  "ESSIKADO  S/S" : "Kobby",
  "FIJIA - TAKORADI" : "Kobby",
  "FUELS  TARKWA)" : "Kobby",
  "HALF ASSINI" : "Kobby",
  "HUTCHFUL" : "Kobby",
  "INCHABAN" : "Kobby",
  "KOJOKROM" : "Kobby",
  "KWADOAGYA" : "Kobby",
  "MANKESSIM MAIN" : "Kobby",
  "NANKABA" : "Kobby",
  "PRESTEA" : "Kobby",
  "SEKONDI ROAD S/S" : "Kobby",
  "SIWDO S/S" : "Kobby",
  "TARKWA BOBOOBO" : "Kobby",
  "TARKWA BONSASO" : "Kobby",
  "TARKWA" : "Kobby",
  "TWIFO PRASO" : "Kobby",
  "WASSA AKROPONG" : "Kobby",
  "WEST ANAJI  S/S" : "Kobby",

  //TEMA STATIONS
  "ABATTOIR" : "Obeng",
  "ABEKOPE" : "Obeng",
  "ADA FOAH" : "Obeng",
  "ADJUMADOR" : "Obeng",
  "AFIENYA MATAHEKO" : "Obeng",
  "AFIENYA TOLL-BOOTH" : "Obeng",
  "AFLAO" : "Obeng",
  "ANLOGA" : "Obeng",
  "ASHAIMAN ZENU" : "Obeng",
  "ASHIAMAN SEC. SCH" : "Obeng",
  "ASHIAMAN VALCO FLATS" : "Obeng",
  "ATIMPOKU" : "Obeng",
  "BETHLEHEM" : "Obeng",
  "BORTEYMAN" : "Obeng",
  "COMMUNITY 1" : "Obeng",
  "COMMUNITY 9" : "Obeng",
  "DAMBAI" : "Obeng",
  "DAWHENYA" : "Obeng",
  "DAWHENYA - ADJUMADOR" : "Obeng",
  "DENU TORKOR" : "Obeng",
  "DENU BARRIER" : "Obeng",
  "DEVTRACO" : "Obeng",
  "DORYUMU" : "Obeng",
  "DZODZE AKANU" : "Obeng",
  "GBETSILE" : "Obeng",
  "GPHA" : "Obeng",
  "HO HOSPITAL ROAD" : "Obeng",
  "HO MAIN" : "Obeng",
  "HO MARKET" : "Obeng",
  "HO OLA" : "Obeng",
  "HOHOE FIRE SERVICE" : "Obeng",
  "HOHOE KPOETA" : "Obeng",
  "HOHOE MAIN" : "Obeng",
  "HOSOKODE" : "Obeng",
  "JASIKAN" : "Obeng",
  "KATAMANSO" : "Obeng",
  "KETA KEDZI" : "Obeng",
  "KETE KRACHI NO.1" : "Obeng",
  "KLAGON" : "Obeng",
  "KOKOMPE" : "Obeng",
  "KPANDO" : "Obeng",
  "KPONE KOKOMPE" : "Obeng",
  "KPONE JUNCTION" : "Obeng",
  "KPONG" : "Obeng",
  "KPONG KOTOKOLI" : "Obeng",
  "KRACHI NO. 1" : "Obeng",
  "LARPLEKU" : "Obeng",
  "LASHIBI" : "Obeng",
  "NUNGUA CHANNEL 5" : "Obeng",
  "SEBREBO" : "Obeng",
  "SHAI HILLS" : "Obeng",
  "SOGAKOPE" : "Obeng",
  "SOMANYA SKED" : "Obeng",
  "SOMANYA TROM" : "Obeng",
  "TEMA COMM.1 MARKET" : "Obeng",
  "TEMA COMM.9" : "Obeng",
  "TRUST LOGISTICS LIMITED - TEMA" : "Obeng",
  "TSOPOLI"  : "Obeng",
  "VRA JUNCTION" : "Obeng",

  //Musah and Musah East

  "ABEHENASE-AMASAMAN" : "Ofori",
  "ABLADJEI" : "Musah",
  "ABLEKUMA NSUFA" : "Musah",
  "ABLEKUMA" : "Musah",
  "ABOADZE AGONA NKWANTA" : "Musah",
  "ABOADZE" : "Musah",
  "ABOKOBI TEIMAN" : "Ofori",
  "ABURI GYANKAMA" : "Ofori",
  "ACHIASE" : "Ofori",
  "ADDY JUNCTION" : "Musah",
  "ADUMANYA S/S" : "Ofori",
  "AGONA MENSAKROM" : "Ofori",
  "AGONA SWEDRU" : "Ofori",
  "AHSALAJA AYIKAI DOBLE" : "Ofori",
  "AKIM ACHIASE" : "Ofori",
  "AKIM ODA GUGGISBURG" : "Ofori",
  "AKIM ODA" : "Ofori",
  "AKIM SUBI" : "Ofori",
  "AKOTSI S/S" : "Ofori",
  "AKWETEYMAN" : "Musah",
  "AMRAHIA" : "Ofori",
  "ANYINAM" : "Ofori",
  "APOLONIA CITY" : "Ofori",
  "ASAMANKESE" : "Ofori",
  "ASHALLEY BOTWE HIGHWAYS" : "Musah",
  "ASHIYIE FULANI JUNCTION" : "Ofori",
  "ASHIYIE-AMPOMAH JUNCTION" : "Ofori",
  "ASHONGMAN" : "Musah",
  "ASOMANING D.O" : "Ofori",
  "ATIBIE AMANFROM" : "Ofori",
  "ATIBIE" : "Ofori",
  "ATUABO" : "Musah",
  "AVIATION" : "Musah",
  "AWUDU ISSAKA(WASSA AKROPONG)" : "Musah",
  "AWUTU BEREKU" : "Ofori",
  "AWUTU" : "Ofori",
  "AYIKA DOBLO JIDA/SOWUTUOM" : "Ofori",
  "AYIKAI DOBLO (ASHALAGA)" : "Ofori",
  "AYIKAI DOBLO" : "Ofori",
  "BEGRO / OSIEM" : "Ofori",
  "BREKUSU" : "Musah",
  "BUDUBURAM" : "Ofori",
  "BUNSO" : "Ofori",
  "CAPE COAST BYPASS" : "Musah",
  "CAPITAL HILL" : "Musah",
  "CHAPEL HILL" : "Musah",
  "CIRCLE CAPRICE" : "Musah",
  "CIRCLE OVERHEAD" : "Musah",
  "DAMFA" : "Ofori",
  "DANSOMAN MAIN" : "Musah",
  "DANSOMAN ROUNDABOUT" : "Musah",
  "DARKUMAN KOKOMPE" : "Musah",
  "DARKUMAN POST OFFICE" : "Musah",
  "DARKUMAN" : "Musah",
  "DODOWA MARKET" : "Ofori",
  "EDWARD LARBI KWAPONG(AKWAKROM)" : "Musah",
  "FAUSTINA MARTIN DANIELS-BAKAANO CAPE COAST" : "Musah",
  "FETTEH  KAKRABA" : "Ofori",
  "GOMOA BIAKOYE" : "Ofori",
  "GOMOA FETTEH" : "Ofori",
  "GOMOA OJOBI" : "Ofori",
  "HEBRON" : "Ofori",
  "IRON CITY" : "Musah",
  "JOSEPH AIDOO (FIJIA - TAKORADI)" : "Musah",
  "KADE" : "Ofori",
  "KASOA KRISPOL CITY" : "Musah",
  "KASOA NEW MARKET" : "Musah",
  "KOFORIDUA ADWESO" : "Ofori",
  "KOFORIDUA ASOKORE" : "Ofori",
  "KOFORIDUA HUHUNYA" : "Ofori",
  "KOFORIDUA OKOENYA" : "Ofori",
  "KOFORIDUA OKORASE" : "Ofori",
  "KOFORIDUA SUHUM" : "Ofori",
  "KOKROBITE" : "Musah",
  "KORKORJOR" : "Musah",
  "KUKURANTUMI" : "Ofori",
  "KUNTUNSE" : "Ofori",
  "KWABENYA MAIN" : "Musah",
  "KWAFOKROM" : "Ofori",
  "LIBERATION ROAD (AIRPORT)" : "Musah",
  "LINK ROAD" : "Musah",
  "MADINA  ESTATE S/S" : "Musah",
  "MADINA ZONGO JUNCTION" : "Musah",
  "MALLAM JUNCTION" : "Musah",
  "MALLAM MARKET" : "Musah",
  "MAMPONG AKWAPIM" : "Ofori",
  "MAYERA" : "Musah",
  "MILE 11" : "Musah",
  "MMT CAPE COAST" : "Musah",
  "MMT TAKORADI" : "Musah",
  "NIMA" : "Musah",
  "NKAWANDA" : "Musah",
  "NSAWAM LORRY PARK" : "Ofori",
  "NSAWAM POLICE STATION" : "Ofori",
  "NYANYANO KAKRABA" : "Musah",
  "NYANYANO RD" : "Musah",
  "NYANYANYO TOWN" : "Musah",
  "NYANYNOR ADADE" : "Musah",
  "OBEYEYIE" : "Ofori",
  "OBUOM RD" : "Musah",
  "ODOKOR BUSIA S/S" : "Musah",
  "OKOBEYEYIE NSAWAM" : "Musah",
  "OYARIFA" : "Ofori",
  "OYIBI" : "Ofori",
  "PALLADIUM" : "Musah",
  "POBIMAN" : "Ofori",
  "PRESEC" : "Musah",
  "RACE COURSE" : "Musah",
  "SANTOE" : "Musah",
  "SAPEIMAN" : "Ofori",
  "SOUTH LA" : "Musah",

  "SOWUTUOM" : "Ofori",
  "STC" : "Musah",
  "SUHUM MAIN ROAD" : "Ofori",
  "SUPERIOR OIL-ELMINA" : "Musah",
  "SUPERIOR OIL-ELUBO" : "Musah",
  "TABORA" : "Musah",
  "TAIFA" : "Musah",
  "TANTRA HILL" : "Musah",
  "TEIMAN (ABOKOBI)" : "Musah",
  "TEMA VRA JUNCTION" : "Musah",
  "TOMAN" : "Ofori",
  "TOMAN-AMASAMAN" : "Ofori",
  "TOUGA JUNCTION" : "Ofori",
  "TSE ADDO" : "Musah",
  "TUBA  BY PASS" : "Musah",
  "VERA DORKUTSO(ADANDZIE)" : "Musah",
  "WEIJA 2" : "Musah",
  "WEIJA WHITE CROSS" : "Musah ",
  "WINNEBA UNIVERSITY" : "Ofori",



};

Future<void> uploadStations() async {
  final db = FirebaseFirestore.instance;

  for (var entry in stations.entries) {
    await db.collection('All Stations').doc(entry.key).set({
      'name': entry.key,
      'ME': entry.value, // zone stored as ME
      'createdAt': FieldValue.serverTimestamp(),
    });
  }

  print("Stations uploaded successfully with ME (zones)!");
}

class UploadStationsPage extends StatelessWidget {
  const UploadStationsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Upload Stations")),
      body: Center(
        child: ElevatedButton(
          child: Text("Upload All Stations"),
          onPressed: () async {
            await uploadStations();
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text("Stations uploaded successfully!")),
            );
          },
        ),
      ),
    );
  }
}


