// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKpEFTA7WQIUw1CDoxosspBhBBQoP8D74',
    appId: '1:478273669259:web:76f548ef395b2d0821ec8e',
    messagingSenderId: '478273669259',
    projectId: 'goil-plc',
    authDomain: 'goil-plc.firebaseapp.com',
    storageBucket: 'goil-plc.firebasestorage.app',
    measurementId: 'G-R673M1RYDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpkmeoOxeD5l1VMd_KRuoV4P6dpmP62po',
    appId: '1:478273669259:android:f69f22439c1fa6e421ec8e',
    messagingSenderId: '478273669259',
    projectId: 'goil-plc',
    storageBucket: 'goil-plc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrkUkWdKJ164yF79MGbkvKspQfIuHboKU',
    appId: '1:478273669259:ios:87eb2a88f1d2d54521ec8e',
    messagingSenderId: '478273669259',
    projectId: 'goil-plc',
    storageBucket: 'goil-plc.firebasestorage.app',
    iosBundleId: 'com.goploglogpump.gopumplog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrkUkWdKJ164yF79MGbkvKspQfIuHboKU',
    appId: '1:478273669259:ios:87eb2a88f1d2d54521ec8e',
    messagingSenderId: '478273669259',
    projectId: 'goil-plc',
    storageBucket: 'goil-plc.firebasestorage.app',
    iosBundleId: 'com.goploglogpump.gopumplog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKpEFTA7WQIUw1CDoxosspBhBBQoP8D74',
    appId: '1:478273669259:web:7decc94bb59bc16f21ec8e',
    messagingSenderId: '478273669259',
    projectId: 'goil-plc',
    authDomain: 'goil-plc.firebaseapp.com',
    storageBucket: 'goil-plc.firebasestorage.app',
    measurementId: 'G-HVT5L3EKBE',
  );
}
